import { createParkingUi,ensureParkingView,OCCUPANCY_LABELS } from "./console.mjs?v=20260819-parking2";

const AMENITY_LABELS=Object.freeze({toilet:"Туалет",shower:"Душ",restaurant:"Еда",shop:"Магазин",wifi:"Wi‑Fi",laundry:"Стирка",water:"Вода",accommodation:"Ночлег",vending:"Автоматы",diesel:"Diesel",adblue:"AdBlue",lng:"LNG",hydrogen:"H₂",evCharging:"Зарядка",frigoPower:"Frigo power",truckWash:"Мойка",truckRepair:"Сервис"});
const SECURITY_LABELS=Object.freeze({restrictedAccess:"Контроль въезда",cctv:"Камеры",guard:"Охрана",fence:"Огорожен",gate:"Шлагбаум",lighting:"Освещение",personalAccessControl:"Контроль личности"});
const FIT_LABELS=Object.freeze({length_limit:"Слишком длинная машина",height_limit:"Ограничение высоты",weight_limit:"Ограничение массы",adr_not_supported:"ADR не подтверждён",frigo_power_missing:"Нет питания для холодильника",security_required:"Не соответствует требованию безопасности"});
const ERROR_LABELS=Object.freeze({parking_location_required:"Для live-статуса включите GPS Driver и обновите позицию.",parking_report_too_far:"Live-статус можно отправить только рядом с паркингом.",parking_rate_limited:"Слишком много действий подряд.",parking_possible_duplicate:"Похожий паркинг уже существует рядом."});
function node(tag,cls,text=""){const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n;}
function action(text,handler,cls=""){const b=node("button",cls,text);b.type="button";b.addEventListener("click",handler);return b;}
function fmtDistance(value){return value===null||value===undefined?"":value<1?`${Math.round(value*1000)} м`:`${Number(value).toFixed(value<10?1:0)} км`;}
function time(value){if(!value)return "";try{return new Date(value).toLocaleString();}catch{return value;}}
function cert(level){return level&&level!=="NONE"?`EU ${level}`:"";}
function occupancyClass(status){return status==="AVAILABLE"?"good":status==="LIMITED"?"warn":["FULL","CLOSED"].includes(status)?"danger":"";}
function dialog(titleText){const d=node("dialog","parking-dialog"),h=node("h3","",titleText),body=node("div"),menu=document.createElement("menu"),close=action("Закрыть",()=>d.close());menu.append(close);d.append(h,body,menu);document.body.append(d);d.addEventListener("close",()=>d.remove(),{once:true});d.showModal();return {dialog:d,body,menu};}
function ratingSelect(label){const wrap=node("label","",label),select=document.createElement("select");select.innerHTML='<option value="5">5 — отлично</option><option value="4">4 — хорошо</option><option value="3">3 — нормально</option><option value="2">2 — плохо</option><option value="1">1 — очень плохо</option>';wrap.append(select);return {wrap,select};}

export function createParkingController({api,uploadBinary,onAuthLost,showError}){
  const ui=createParkingUi(ensureParkingView());let profileReady=false,places=[],selected=null,location=null;
  function setState(text,kind=""){ui.state.textContent=text;ui.state.dataset.state=kind;}
  function handle(error,message="Не удалось выполнить действие."){if(error?.status===401)return onAuthLost?.();const text=ERROR_LABELS[error?.message]||message;showError?.(text);setState(text,"error");}
  function getPosition({silent=false}={}){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error("geolocation_unavailable"));navigator.geolocation.getCurrentPosition(p=>{location={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy};resolve(location);},e=>{if(!silent)showError?.("Не удалось получить геопозицию для поиска парковок.");reject(e);},{enableHighAccuracy:false,timeout:9000,maximumAge:60000});});}
  function queryPath(){const p=new URLSearchParams();if(location){p.set("lat",location.latitude);p.set("lon",location.longitude);}p.set("radiusKm",ui.controls.radius.value);if(ui.controls.query.value.trim())p.set("q",ui.controls.query.value.trim());if(ui.controls.occupancy.value)p.set("availableOnly","1");if(ui.controls.amenity.value)p.set("amenities",ui.controls.amenity.value);if(ui.controls.security.value)p.set("security",ui.controls.security.value);if(ui.controls.certification.value&&ui.controls.certification.value!=="NONE")p.set("certification",ui.controls.certification.value);if(ui.controls.booking.value)p.set("reservable","1");return `/api/driver/parking/search?${p}`;}
  function renderList(){ui.list.replaceChildren();if(!places.length){ui.list.append(node("div","parking-empty","Паркинги не найдены. Измените фильтры или добавьте отсутствующий."));return;}for(const place of places){const row=action("",()=>openPlace(place.id));row.className="parking-row";row.classList.toggle("active",Number(selected?.id)===Number(place.id));const dot=node("span","parking-status-dot",OCCUPANCY_LABELS[place.occupancy?.status]||"?");dot.dataset.status=place.occupancy?.status||"UNKNOWN";const copy=node("span"),name=node("strong","",`${place.favorite?"★ ":""}${place.name}`),summary=node("small","",[place.road,place.countryCode,cert(place.security?.certificationLevel),place.booking?.reservable?"бронь":""].filter(Boolean).join(" · "));copy.append(name,summary);const meta=node("span","parking-row-meta");meta.append(node("span","",fmtDistance(place.distanceKm??place.routeDistanceKm)),node("small","",place.reviews?.overall?`★ ${place.reviews.overall}`:`fit ${place.fit?.score??"?"}`));row.append(dot,copy,meta);ui.list.append(row);}}
  function badge(text,cls=""){return node("span",`parking-badge ${cls}`,text);}
  function dl(entries){const list=node("dl","parking-kv");for(const [k,v] of entries){if(v===null||v===undefined||v==="")continue;list.append(node("dt","",k),node("dd","",String(v)));}return list;}
  async function loadSearch(){if(!profileReady)return;setState("Ищем паркинги…");try{const data=await api(queryPath());places=data.places||[];renderList();setState(`Найдено: ${places.length}`);if(selected&&!places.some(p=>p.id===selected.id))selected=null;}catch(e){handle(e,"Не удалось загрузить паркинги.");}}
  async function openPlace(id){try{const q=location?`?lat=${location.latitude}&lon=${location.longitude}`:"";const data=await api(`/api/driver/parking/places/${id}${q}`);selected=data.place;renderList();renderDetail(data);setState("Карточка паркинга открыта.");}catch(e){handle(e,"Не удалось открыть паркинг.");}}

  function renderDetail(data){
    const p=data.place;ui.detail.replaceChildren();const head=node("div","parking-detail-head"),copy=node("div");copy.append(node("h3","",p.name),node("div","parking-state",[p.address,p.road,p.direction].filter(Boolean).join(" · ")));const fav=action(p.favorite?"★":"☆",async()=>{try{await api(`/api/driver/parking/places/${p.id}/favorite`,{method:"PUT",body:{enabled:!p.favorite}});await openPlace(p.id);await loadSearch();}catch(e){handle(e);}});head.append(copy,fav);ui.detail.append(head);
    const badges=node("div","parking-badges");badges.append(badge(OCCUPANCY_LABELS[p.occupancy.status]||p.occupancy.status,occupancyClass(p.occupancy.status)));if(p.occupancy.predicted)badges.append(badge(`Прогноз · ${Math.round(p.occupancy.confidence*100)}%`,"warn"));else if(p.occupancy.updatedAt)badges.append(badge(`${p.occupancy.source} · ${Math.round(p.occupancy.confidence*100)}%`));if(cert(p.security.certificationLevel))badges.append(badge(cert(p.security.certificationLevel),"good"));if(p.status==="COMMUNITY_UNVERIFIED")badges.append(badge("Добавлено водителем · не подтверждено","warn"));badges.append(!p.fit.compatible?badge("Не подходит машине","danger"):badge(`Совместимость ${p.fit.score}%`,p.fit.score>=80?"good":"warn"));ui.detail.append(badges);
    if(p.fit.issues?.length)ui.detail.append(node("div","parking-state",p.fit.issues.map(x=>FIT_LABELS[x]||x).join(" · ")));
    const actions=node("div","parking-actions");const route=node("a","primary","Маршрут");route.href=`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${p.latitude},${p.longitude}`)}`;route.target="_blank";route.rel="noreferrer noopener";actions.append(route);if(p.booking?.reservable&&p.booking.url){const a=node("a","primary","Забронировать");a.href=p.booking.url;a.target="_blank";a.rel="noreferrer noopener";actions.append(a);}if(p.phone){const a=node("a","","Позвонить");a.href=`tel:${p.phone}`;actions.append(a);}if(p.website){const a=node("a","","Сайт");a.href=p.website;a.target="_blank";a.rel="noreferrer noopener";actions.append(a);}actions.append(action("Сообщить занятость",()=>showOccupancyDialog(p)),action("Отзыв",()=>showReviewDialog(p)),action("Фото",()=>showPhotoDialog(p)),action("Исправить",()=>showCorrectionDialog(p)));ui.detail.append(actions);
    const info=node("div","parking-section");info.append(dl([["Расстояние",fmtDistance(p.distanceKm)],["Мест TIR",p.capacity.truck],["Режим",p.access24h?"24/7":p.openingHours],["Оплата",p.fee.priceText||p.fee.mode],["Оператор",p.operator],["Бронь",p.booking.reservable?p.booking.provider||"доступна":"нет данных"],["Источник live",p.occupancy.source],["Live обновлено",time(p.occupancy.updatedAt)],["Достоверность данных",`${Math.round(p.dataConfidence*100)}%`]]));ui.detail.append(info);
    const amenSec=node("div","parking-section");amenSec.append(node("h4","","Услуги"));const amenities=node("div","parking-amenities");for(const [key,label] of Object.entries(AMENITY_LABELS))if(p.amenities[key])amenities.append(badge(label,"good"));if(!amenities.children.length)amenities.append(node("span","parking-state","Услуги не подтверждены."));amenSec.append(amenities,node("h4","","Безопасность"));const security=node("div","parking-amenities");for(const [key,label] of Object.entries(SECURITY_LABELS))if(p.security[key])security.append(badge(label,"good"));if(!security.children.length&&!cert(p.security.certificationLevel))security.append(node("span","parking-state","Данные о безопасности не подтверждены."));amenSec.append(security);ui.detail.append(amenSec);
    const reviews=node("div","parking-section");reviews.append(node("h4","",`Отзывы · ${p.reviews.count}${p.reviews.overall?` · ★ ${p.reviews.overall}`:""}`));if(p.reviews.count)reviews.append(node("div","parking-state",[`Безопасность ${p.reviews.security??"—"}`,`Чистота ${p.reviews.cleanliness??"—"}`,`Заезд ${p.reviews.access??"—"}`,`Тишина ${p.reviews.quietness??"—"}`].join(" · ")));for(const r of (data.reviews||[]).slice(0,8)){const item=node("article","parking-state");item.append(node("strong","",`${r.author} · ★ ${r.overall}`),node("p","",r.text||"Без текста"));reviews.append(item);}ui.detail.append(reviews);
    if(data.photos?.length){const sec=node("div","parking-section");sec.append(node("h4","","Фото"));const grid=node("div","parking-photo-grid");for(const photo of data.photos){const img=document.createElement("img");img.src=photo.url;img.alt=`Фото паркинга ${p.name}`;img.loading="lazy";grid.append(img);}sec.append(grid);ui.detail.append(sec);}
    if(data.alternatives?.length){const sec=node("div","parking-section");sec.append(node("h4","","План Б рядом"));for(const alt of data.alternatives)sec.append(action(`${OCCUPANCY_LABELS[alt.occupancy.status]||"?"} · ${alt.name} · ${fmtDistance(alt.distanceKm)}`,()=>openPlace(alt.id)));ui.detail.append(sec);}
    if(p.sources?.length){const sec=node("div","parking-section");sec.append(node("h4","","Источники"));for(const s of p.sources)sec.append(node("div","parking-state",`${s.type} · ${s.name||"источник"} · authority ${s.authority}${s.sourceUpdatedAt?` · ${time(s.sourceUpdatedAt)}`:""}`));ui.detail.append(sec);}
  }

  function showOccupancyDialog(p){const d=dialog("Что сейчас с местами?");const grid=node("div","parking-live-actions");for(const [status,label] of Object.entries({AVAILABLE:"Есть места",LIMITED:"Мало мест",FULL:"Полный",CLOSED:"Закрыт"}))grid.append(action(label,async()=>{try{await api(`/api/driver/parking/places/${p.id}/occupancy`,{method:"POST",body:{status}});d.dialog.close();await openPlace(p.id);await loadSearch();}catch(e){handle(e);}}));d.body.append(grid,node("p","parking-state","Live-отчёт принимается только от водителя со свежим Driver GPS не дальше 3 км и затем автоматически устаревает."));}
  function showReviewDialog(p){const d=dialog(`Отзыв · ${p.name}`),form=node("form","parking-form"),overall=ratingSelect("Общая оценка"),security=ratingSelect("Безопасность"),cleanliness=ratingSelect("Чистота"),access=ratingSelect("Заезд / доступ"),quietness=ratingSelect("Тишина / отдых"),grid=node("div","parking-rating-grid"),txt=document.createElement("textarea");grid.append(security.wrap,cleanliness.wrap,access.wrap,quietness.wrap);txt.maxLength=1200;txt.placeholder="Что важно знать водителю? Заезд, безопасность, тишина, санитария…";const save=action("Сохранить",()=>{},"primary");save.type="submit";form.append(overall.wrap,grid,txt,save);form.addEventListener("submit",async e=>{e.preventDefault();try{await api(`/api/driver/parking/places/${p.id}/review`,{method:"PUT",body:{overall:Number(overall.select.value),security:Number(security.select.value),cleanliness:Number(cleanliness.select.value),access:Number(access.select.value),quietness:Number(quietness.select.value),text:txt.value}});d.dialog.close();await openPlace(p.id);await loadSearch();}catch(err){handle(err,"Не удалось сохранить отзыв.");}});d.body.append(form);}
  function showPhotoDialog(p){const d=dialog(`Фото · ${p.name}`),input=document.createElement("input");input.type="file";input.accept="image/jpeg,image/png,image/webp";const send=action("Загрузить",async()=>{const file=input.files?.[0];if(!file)return;if(file.size>5*1024*1024)return showError?.("Фото должно быть не больше 5 МиБ.");try{await uploadBinary(`/api/driver/parking/places/${p.id}/photos`,file,{headers:{"X-File-Name":file.name}});d.dialog.close();await openPlace(p.id);}catch(e){handle(e,"Не удалось загрузить фото.");}},"primary");d.body.append(input,send,node("p","parking-state","JPEG, PNG или WebP · максимум 5 МиБ. Сервер проверяет сигнатуру файла."));}
  function showCorrectionDialog(p){const d=dialog(`Исправление · ${p.name}`),form=node("form","parking-form"),kind=document.createElement("select"),txt=document.createElement("textarea");kind.innerHTML='<option value="WRONG_INFO">Неверные данные</option><option value="CLOSED">Закрыт</option><option value="ACCESS">Заезд</option><option value="AMENITY">Услуги</option><option value="SECURITY">Безопасность</option><option value="CAPACITY">Количество мест</option><option value="LOCATION">Координаты</option><option value="OTHER">Другое</option>';txt.required=true;txt.maxLength=800;txt.placeholder="Что именно неверно?";const save=action("Отправить",()=>{},"primary");save.type="submit";form.append(kind,txt,save);form.addEventListener("submit",async e=>{e.preventDefault();try{await api(`/api/driver/parking/places/${p.id}/corrections`,{method:"POST",body:{kind:kind.value,message:txt.value}});d.dialog.close();setState("Исправление отправлено.");}catch(err){handle(err,"Не удалось отправить исправление.");}});d.body.append(form);}
  function showPreferences(current={}){const d=dialog("Моя машина для подбора паркинга"),form=node("form","parking-form"),inputs={};const typeLabel=node("label","","Тип машины"),vehicleClass=document.createElement("select");vehicleClass.innerHTML='<option value="TIR">TIR / грузовик</option><option value="VAN">Фургон</option><option value="CAR">Легковая</option><option value="OTHER">Другое</option>';vehicleClass.value=current.vehicleClass||"TIR";typeLabel.append(vehicleClass);form.append(typeLabel);inputs.vehicleClass=vehicleClass;for(const [name,label] of [['lengthM','Длина, м'],['heightM','Высота, м'],['weightT','Масса, т'],['maxDetourKm','Максимальный крюк, км']]){const l=node("label","",label),i=document.createElement("input");i.type="number";i.step="0.1";i.name=name;if(current?.[name]!==null&&current?.[name]!==undefined)i.value=current[name];l.append(i);form.append(l);inputs[name]=i;}for(const [name,label] of [['adrRequired','ADR'],['refrigerated','Холодильник / нужен frigo power'],['secureOnly','Только безопасные']]){const l=node("label","",label),i=document.createElement("input");i.type="checkbox";i.name=name;i.checked=Boolean(current?.[name]);l.prepend(i);form.append(l);inputs[name]=i;}const save=action("Сохранить",()=>{},"primary");save.type="submit";form.append(save);form.addEventListener("submit",async e=>{e.preventDefault();try{await api("/api/driver/parking/preferences",{method:"PATCH",body:{vehicleClass:inputs.vehicleClass.value,lengthM:inputs.lengthM.value||null,heightM:inputs.heightM.value||null,weightT:inputs.weightT.value||null,maxDetourKm:inputs.maxDetourKm.value||10,adrRequired:inputs.adrRequired.checked,refrigerated:inputs.refrigerated.checked,secureOnly:inputs.secureOnly.checked}});d.dialog.close();await loadSearch();}catch(err){handle(err,"Не удалось сохранить параметры машины.");}});d.body.append(form);}
  function showAddDialog(){const d=dialog("Добавить отсутствующий паркинг"),form=node("form","parking-form"),name=document.createElement("input"),lat=document.createElement("input"),lon=document.createElement("input"),capacity=document.createElement("input");name.placeholder="Название";name.required=true;lat.type=lon.type=capacity.type="number";lat.step=lon.step="0.000001";capacity.step="1";lat.placeholder="Широта";lon.placeholder="Долгота";capacity.placeholder="Мест TIR (если известно)";if(location){lat.value=location.latitude;lon.value=location.longitude;}const use=action("Взять мою геопозицию",async()=>{try{const p=await getPosition();lat.value=p.latitude;lon.value=p.longitude;}catch{}}),save=action("Добавить",()=>{},"primary");save.type="submit";form.append(name,node("div","two"));form.querySelector(".two").append(lat,lon);form.append(capacity,use,save);form.addEventListener("submit",async e=>{e.preventDefault();try{const data=await api("/api/driver/parking/places",{method:"POST",body:{name:name.value,latitude:Number(lat.value),longitude:Number(lon.value),capacityTruck:capacity.value?Number(capacity.value):null,kind:"TRUCK_PARKING"}});d.dialog.close();await loadSearch();await openPlace(data.place.id);}catch(err){handle(err,"Не удалось добавить паркинг.");}});d.body.append(form,node("p","parking-state","Добавленное водителем место получает отметку «не подтверждено», пока его не подтвердит другой источник."));}

  ui.controls.search.addEventListener("submit",e=>{e.preventDefault();loadSearch();});ui.controls.nearby.addEventListener("click",async()=>{try{await getPosition();await loadSearch();}catch{}});ui.controls.favorites.addEventListener("click",async()=>{try{const data=await api("/api/driver/parking/favorites");places=data.places||[];renderList();setState(`Избранных: ${places.length}`);}catch(e){handle(e);}});ui.controls.add.addEventListener("click",showAddDialog);ui.controls.preferences.addEventListener("click",async()=>{try{const data=await api("/api/driver/parking/overview");showPreferences(data.preferences);}catch(e){handle(e);}});
  return {async activate(){if(!profileReady)return setState("Сначала сохраните профиль водителя.","error");if(!places.length){await getPosition({silent:true}).catch(()=>{});await loadSearch();}},setSession({profile}){profileReady=Boolean(profile);},setProfileReady(profile){profileReady=Boolean(profile);},reset(){profileReady=false;places=[];selected=null;location=null;ui.list.replaceChildren();ui.detail.replaceChildren(node("div","parking-empty","Выберите паркинг слева."));setState("Паркинги отключены");}};
}

export function createDriverModule(context){return createParkingController({api:context.api,uploadBinary:context.uploadBinary,onAuthLost:context.onAuthLost,showError:context.showError});}
