function installStyles(){if(document.querySelector("#navigation-search-v1-styles"))return;const style=document.createElement("style");style.id="navigation-search-v1-styles";style.textContent=`.navigation-destination-search{display:grid;gap:6px}.navigation-search-results{display:grid;gap:5px;max-height:210px;overflow:auto}.navigation-search-result{display:grid;gap:2px;text-align:left;padding:8px;border-radius:10px}.navigation-search-result small{opacity:.72}.navigation-search-empty{font-size:.82rem;opacity:.75;padding:4px 2px}`;document.head.append(style);}
function buttonFor(item,onSelect){const button=document.createElement("button");button.type="button";button.className="navigation-search-result";button.setAttribute("role","option");const title=document.createElement("strong");title.textContent=item.kind==="PARKING"?`P · ${item.label}`:item.label;const meta=document.createElement("small");const details=[item.subtitle,item.kind==="PARKING"?item.occupancy?.status:null,item.kind==="PARKING"&&item.fit?.compatible===false?"не подходит профилю":null].filter(Boolean);meta.textContent=details.join(" · ");button.append(title,meta);button.addEventListener("click",()=>onSelect(item));return button;}
export function installDestinationSearch({panel,api,getLocation,showError,onAuthLost}={}){
  installStyles();const form=panel?.panel?.querySelector(".navigation-form"),labelInput=form?.querySelector('input[name="destinationLabel"]');if(!form||!labelInput)return {reset(){}};
  const host=document.createElement("div");host.className="navigation-destination-search";const results=document.createElement("div");results.className="navigation-search-results";results.setAttribute("role","listbox");results.setAttribute("aria-label","Результаты поиска точки назначения");results.hidden=true;labelInput.parentElement.insertAdjacentElement("afterend",host);host.append(results);
  let timer=null,token=0;
  function clear(){results.replaceChildren();results.hidden=true;}
  function select(item){panel.setDestination({latitude:item.latitude,longitude:item.longitude,label:item.label});clear();labelInput.focus();}
  function render(items,query){results.replaceChildren();if(!items.length){const empty=document.createElement("div");empty.className="navigation-search-empty";empty.textContent=`По запросу «${query}» ничего не найдено`;results.append(empty);}else for(const item of items)results.append(buttonFor(item,select));results.hidden=false;}
  async function search(){const query=labelInput.value.trim();const own=typeof getLocation==="function"?getLocation():null,current=++token;if(query.length<2)return clear();try{const params=new URLSearchParams({q:query,limit:"8"});if(own&&Number.isFinite(Number(own.latitude))&&Number.isFinite(Number(own.longitude))){params.set("lat",String(own.latitude));params.set("lon",String(own.longitude));}const data=await api(`/api/driver/navigation/search?${params}`);if(current!==token)return;render(Array.isArray(data.results)?data.results:[],query);}catch(error){if(current!==token)return;clear();if(error?.status===401)return onAuthLost?.();if(error?.message!=="navigation_geocoder_unavailable"&&error?.message!=="navigation_geocoder_timeout")showError?.("Поиск места временно недоступен. Можно выбрать точку на карте.");}}
  labelInput.setAttribute("autocomplete","off");labelInput.setAttribute("aria-autocomplete","list");labelInput.addEventListener("input",()=>{if(timer!==null)window.clearTimeout(timer);timer=window.setTimeout(search,350);});labelInput.addEventListener("keydown",event=>{if(event.key==="Escape")clear();});document.addEventListener("pointerdown",event=>{if(!host.contains(event.target)&&event.target!==labelInput)clear();});
  return {reset(){token++;if(timer!==null)window.clearTimeout(timer);timer=null;clear();}};
}
