const STRATEGIES=[
  ["PRACTICAL_TRUCK","Практичный для грузовика"],["FASTEST_LEGAL","Самый быстрый разрешённый"],["EASY_TRUCK","Проще для грузовика"],["ECONOMY","Экономичный"],["PARKING_AWARE","С приоритетом стоянок"]
];
const TRUCK_ONLY_STRATEGIES=new Set(["PRACTICAL_TRUCK","EASY_TRUCK"]);
function el(tag,className="",text=""){const node=document.createElement(tag);if(className)node.className=className;if(text)node.textContent=text;return node;}
function button(text,handler,className=""){const node=el("button",className,text);node.type="button";if(handler)node.addEventListener("click",handler);return node;}
function fmtDistance(km){const n=Number(km);if(!Number.isFinite(n))return "—";return n<1?`${Math.round(n*1000)} м`:`${n.toFixed(n<10?1:0)} км`;}
function fmtDuration(sec){const n=Number(sec);if(!Number.isFinite(n))return "—";const minutes=Math.max(0,Math.round(n/60)),hours=Math.floor(minutes/60),rest=minutes%60;return hours?`${hours} ч ${rest} мин`:`${rest} мин`;}
function fmtEta(iso){const ms=Date.parse(iso||"");return Number.isFinite(ms)?new Intl.DateTimeFormat("ru",{hour:"2-digit",minute:"2-digit"}).format(ms):"—";}
function installStyles(){if(document.querySelector("#navigation-v1-styles"))return;const style=document.createElement("style");style.id="navigation-v1-styles";style.textContent=`
.map-card{position:relative}.navigation-launch{min-height:38px;white-space:nowrap}.navigation-launch[data-active="true"]{font-weight:800}
.navigation-panel{position:absolute;z-index:24;right:12px;top:76px;width:min(430px,calc(100% - 24px));max-height:calc(100% - 100px);overflow:auto;background:rgba(10,25,22,.97);border:1px solid rgba(255,255,255,.14);border-radius:18px;padding:14px;box-shadow:0 18px 50px rgba(0,0,0,.38);overscroll-behavior:contain}
.navigation-panel[hidden]{display:none}.navigation-panel header{display:flex;align-items:center;justify-content:space-between;gap:8px;position:sticky;top:-14px;background:rgba(10,25,22,.98);padding:10px 0;z-index:2}.navigation-panel h3,.navigation-panel h4{margin:0}.navigation-status{font-size:.82rem;opacity:.82}.navigation-form{display:grid;gap:10px}.navigation-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.navigation-form label{display:grid;gap:4px}.navigation-form input,.navigation-form select{width:100%;box-sizing:border-box}.navigation-actions{display:flex;gap:8px;flex-wrap:wrap}.navigation-actions button{flex:1 1 auto}.navigation-truth{display:grid;gap:5px;padding:9px;border-radius:12px;background:rgba(255,255,255,.05);font-size:.84rem}.navigation-alternatives{display:grid;gap:8px;margin-top:10px}.navigation-alt{display:grid;gap:7px;text-align:left;width:100%;padding:10px;border-radius:13px;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.04)}.navigation-alt[data-selected="true"]{outline:2px solid currentColor}.navigation-alt-main{display:flex;justify-content:space-between;gap:8px}.navigation-alt-meta{font-size:.8rem;opacity:.8}.navigation-guard{padding:9px;border-radius:12px;background:rgba(255,255,255,.05);font-size:.82rem}.navigation-parking-list,.navigation-road-list{display:grid;gap:6px;margin-top:8px}.navigation-mini-card{padding:8px;border-radius:10px;background:rgba(255,255,255,.05);font-size:.82rem}.navigation-guidance{display:grid;gap:10px}.navigation-next{font-size:1.35rem;font-weight:800}.navigation-guidance-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.navigation-metric{padding:8px;border-radius:10px;background:rgba(255,255,255,.06);text-align:center}.navigation-metric strong{display:block}.navigation-offroute{font-weight:800}.navigation-panel[data-moving="true"] .navigation-editing{display:none}.navigation-panel[data-mode="guidance"]{top:82px;left:12px;right:auto;max-height:52%;width:min(470px,calc(100% - 24px))}.navigation-provider-warning{padding:9px;border-radius:10px;background:rgba(255,255,255,.06)}
.navigation-profile-dialog{max-width:560px;width:calc(100% - 24px);max-height:90vh;overflow:auto}.navigation-profile-form{display:grid;gap:10px}.navigation-profile-form .navigation-grid{grid-template-columns:repeat(2,minmax(0,1fr))}
@media(max-width:700px){.navigation-panel{left:8px;right:8px;top:auto;bottom:64px;width:auto;max-height:55%;border-radius:16px}.navigation-panel[data-mode="guidance"]{left:8px;right:8px;top:72px;bottom:auto;width:auto;max-height:43%}.navigation-profile-form .navigation-grid{grid-template-columns:1fr}.navigation-guidance-metrics{grid-template-columns:repeat(3,minmax(0,1fr));font-size:.82rem}}
`;document.head.append(style);}
function input(type,name,value=""){const node=document.createElement("input");node.type=type;node.name=name;if(value!==null&&value!==undefined)node.value=value;return node;}
function field(labelText,node){const label=el("label");label.append(el("span","",labelText),node);return label;}
function numberOrNull(value){return value===""?null:Number(value);}

export function createNavigationPanel({onPickDestination,onCalculate,onSaveProfile,onSelectAlternative,onStart,onReroute,onFinish,onFit,onOpenParking}={}){
  installStyles();const card=document.querySelector("#map-view .map-card");const heading=card?.querySelector(".map-heading");if(!card||!heading)throw new Error("navigation_map_host_missing");
  const launch=button("Маршрут",()=>toggle(),"navigation-launch");launch.setAttribute("aria-expanded","false");heading.append(launch);
  const panel=el("aside","navigation-panel");panel.hidden=true;panel.dataset.mode="planner";panel.setAttribute("aria-label","Навигация и маршрут");
  const header=document.createElement("header"),title=el("h3","","Маршрут"),state=el("span","navigation-status","Подготовка…"),close=button("×",()=>closePanel());close.setAttribute("aria-label","Закрыть навигацию");header.append(title,state,close);
  const providerNote=el("div","navigation-provider-warning");
  const planner=el("section","navigation-editing");const form=el("form","navigation-form");
  const destinationLabel=input("text","destinationLabel");destinationLabel.placeholder="Название точки (необязательно)";
  const lat=input("number","latitude"),lon=input("number","longitude");lat.step=lon.step="any";lat.min="-90";lat.max="90";lon.min="-180";lon.max="180";lat.required=true;lon.required=true;
  const pick=button("Выбрать точку на карте",async()=>{pick.disabled=true;try{const point=await onPickDestination?.();if(point)setDestination(point);}finally{pick.disabled=false;}});
  const strategy=document.createElement("select");for(const [value,label] of STRATEGIES){const option=document.createElement("option");option.value=value;option.textContent=label;strategy.append(option);}
  const breakEnabled=input("checkbox","breakEnabled"),remaining=input("number","remainingDriveMinutes","180");remaining.min="0";remaining.max="600";remaining.step="5";
  const breakRow=el("div","navigation-grid");breakRow.append(field("Планировать перерыв",breakEnabled),field("Осталось вождения, мин",remaining));
  const calculate=button("Рассчитать маршрут",null,"primary");calculate.type="submit";const vehicle=button("Профиль машины",()=>openProfile());
  const truth=el("div","navigation-truth");truth.append(el("span","","Трафик: источник не подключён"),el("span","","Стоимость платных дорог: источник не подключён"),el("span","","Маршрут проверяется по профилю автомобиля; неизвестные ограничения не скрываются."));
  form.append(field("Точка назначения",destinationLabel),el("div","navigation-grid"));form.querySelector(".navigation-grid").append(field("Широта",lat),field("Долгота",lon));form.append(pick,field("Стратегия",strategy),breakRow,el("div","navigation-actions"),truth);form.querySelector(".navigation-actions").append(calculate,vehicle);
  form.addEventListener("submit",async event=>{event.preventDefault();calculate.disabled=true;try{await onCalculate?.(getRequest());}finally{calculate.disabled=false;}});planner.append(form);
  const guardBox=el("div","navigation-guard");guardBox.hidden=true;const alternatives=el("div","navigation-alternatives"),parking=el("div","navigation-parking-list"),roads=el("div","navigation-road-list");
  const guidance=el("section","navigation-guidance");guidance.hidden=true;const next=el("div","navigation-next","Маршрут готов"),offroute=el("div","navigation-offroute"),metrics=el("div","navigation-guidance-metrics");const metricDistance=el("div","navigation-metric"),metricTime=el("div","navigation-metric"),metricEta=el("div","navigation-metric");metrics.append(metricDistance,metricTime,metricEta);const guidanceActions=el("div","navigation-actions");guidanceActions.append(button("Маршрут целиком",()=>onFit?.()),button("Перестроить",()=>onReroute?.()),button("Plan B",()=>onOpenParking?.()),button("Завершить",()=>onFinish?.()));guidance.append(next,offroute,metrics,guidanceActions,parking,roads);
  panel.append(header,providerNote,planner,guardBox,alternatives,guidance);card.append(panel);

  let profile=null,currentRoute=null;
  function openPanel(mode="planner"){panel.hidden=false;panel.dataset.mode=mode;launch.dataset.active="true";launch.setAttribute("aria-expanded","true");}
  function closePanel(){panel.hidden=true;launch.dataset.active="false";launch.setAttribute("aria-expanded","false");}
  function toggle(){panel.hidden?openPanel(currentRoute?"guidance":"planner"):closePanel();}
  function setDestination(point){lat.value=Number(point.latitude).toFixed(6);lon.value=Number(point.longitude).toFixed(6);if(point.label)destinationLabel.value=point.label;}
  function getRequest(){return {destination:{latitude:numberOrNull(lat.value),longitude:numberOrNull(lon.value),label:destinationLabel.value.trim()},strategy:strategy.value,alternatives:3,break:{enabled:breakEnabled.checked,remainingDriveMinutes:Number(remaining.value),desiredBreakMinutes:45}};}
  function syncStrategyOptions(vehicleClass){const isTruck=vehicleClass==="TRUCK";for(const option of strategy.options)option.disabled=!isTruck&&TRUCK_ONLY_STRATEGIES.has(option.value);if(strategy.selectedOptions[0]?.disabled)strategy.value="FASTEST_LEGAL";}
  function setProviderStatus(status){const router=status?.router;state.textContent=router?.configured?`Маршрутизатор: ${router.name}`:"Маршрутизатор не подключён";providerNote.textContent=router?.configured?`${router.name}: строгая маршрутизация включена. Трафик и стоимость платных дорог показываются только при наличии отдельного источника.`:"Сервер маршрутизации пока не настроен. Профиль и интерфейс доступны, но PaTaP не будет рисовать выдуманный маршрут.";calculate.disabled=!router?.configured;truth.children[0].textContent=`Трафик: ${status?.traffic?.configured?`источник ${status.traffic.source}`:"источник не подключён"}`;truth.children[1].textContent=`Стоимость платных дорог: ${status?.tolls?.configured?`источник ${status.tolls.source}`:"источник не подключён"}`;}
  function setProfile(nextProfile){profile=nextProfile||null;syncStrategyOptions(profile?.vehicleClass||"TRUCK");if(profile?.preferredStrategy&&!strategy.querySelector(`option[value="${profile.preferredStrategy}"]`)?.disabled)strategy.value=profile.preferredStrategy;}
  function openProfile(){
    const value=profile||{};const dialog=el("dialog","navigation-profile-dialog"),profileForm=el("form","navigation-profile-form"),profileHeading=el("h3","","Профиль машины для маршрута");const vehicleClass=document.createElement("select");for(const v of ["TRUCK","VAN","CAR","TAXI","OTHER"]){const o=document.createElement("option");o.value=v;o.textContent=v;o.selected=v===(value.vehicleClass||"TRUCK");vehicleClass.append(o);}
    const fields={lengthM:input("number","lengthM",value.lengthM??""),widthM:input("number","widthM",value.widthM??""),heightM:input("number","heightM",value.heightM??""),grossWeightT:input("number","grossWeightT",value.grossWeightT??""),axleLoadT:input("number","axleLoadT",value.axleLoadT??""),axleCount:input("number","axleCount",value.axleCount??""),maxSpeedKph:input("number","maxSpeedKph",value.maxSpeedKph??"")};for(const node of Object.values(fields))node.step="any";
    const grid=el("div","navigation-grid");grid.append(field("Длина, м",fields.lengthM),field("Ширина, м",fields.widthM),field("Высота, м",fields.heightM),field("Полный вес, т",fields.grossWeightT),field("Нагрузка на ось, т",fields.axleLoadT),field("Количество осей",fields.axleCount),field("Ограничитель скорости, км/ч",fields.maxSpeedKph));
    const hazmat=input("checkbox","hazardousGoods");hazmat.checked=Boolean(value.hazardousGoods);const refrigerated=input("checkbox","refrigerated");refrigerated.checked=Boolean(value.refrigerated);const trailer=input("checkbox","trailer");trailer.checked=Boolean(value.trailer);const adr=document.createElement("select");for(const code of ["NONE","A","B","C","D","E"]){const o=document.createElement("option");o.value=code;o.textContent=code;o.selected=code===(value.adrTunnelCode||"NONE");adr.append(o);}
    const checks=el("div","navigation-grid");checks.append(field("Класс",vehicleClass),field("ADR тоннель",adr),field("Опасный груз",hazmat),field("Рефрижератор",refrigerated),field("Прицеп",trailer));const actions=el("div","navigation-actions"),cancel=button("Отмена",()=>dialog.close()),save=button("Сохранить",null,"primary");save.type="submit";actions.append(cancel,save);profileForm.append(profileHeading,el("p","navigation-status","Для TRUCK высота, ширина, длина и полный вес обязательны. Без них PaTaP не строит грузовой маршрут."),checks,grid,actions);dialog.append(profileForm);document.body.append(dialog);dialog.addEventListener("close",()=>dialog.remove(),{once:true});profileForm.addEventListener("submit",async event=>{event.preventDefault();save.disabled=true;try{const payload={vehicleClass:vehicleClass.value,adrTunnelCode:adr.value,hazardousGoods:hazmat.checked,refrigerated:refrigerated.checked,trailer:trailer.checked};for(const [key,node] of Object.entries(fields))payload[key]=node.value===""?null:Number(node.value);const saved=await onSaveProfile?.(payload);if(saved){setProfile(saved);dialog.close();}}finally{save.disabled=false;}});dialog.showModal();
  }
  function renderGuard(route){const guard=route?.routeGuard;if(!guard){guardBox.hidden=true;return;}guardBox.hidden=false;const labels=[`Route Guard: ${guard.level||"UNKNOWN"} · ${Math.round(Number(guard.confidence||0)*100)}%`,`Профиль ограничений: ${guard.strictVehicleProfile?"строгий":"есть неподтверждённые ограничения"}`];if(guard.warnings?.length)labels.push(`Предупреждения: ${guard.warnings.join(", ")}`);if(guard.unknowns?.length)labels.push(`Нет данных: ${guard.unknowns.join(", ")}`);guardBox.replaceChildren(...labels.map(x=>el("div","",x)));}
  function renderLists(route){parking.replaceChildren();roads.replaceChildren();const enrichment=route?.enrichment?.[route.selectedAlternativeId]||route?.enrichment||{};const places=enrichment?.parking?.recommendedStops||[];if(places.length){parking.append(el("h4","","Стоянки по маршруту"));for(const place of places.slice(0,4)){const card=button("",()=>onOpenParking?.(place),"navigation-mini-card");card.textContent=`${place.name} · ${place.occupancy?.status||"UNKNOWN"} · +${fmtDistance(place.routeDistanceKm)} · ~${place.routeEtaMinutes??"?"} мин`;parking.append(card);}const advisory=enrichment?.parking?.breakAdvisory;if(advisory)parking.append(el("div","navigation-mini-card",advisory.warning));}
    const events=enrichment?.roadEvents||[];if(events.length){roads.append(el("h4","","События впереди"));for(const report of events.slice(0,5))roads.append(el("div","navigation-mini-card",`${report.type} · ${fmtDistance(report.route?.distanceFromStartKm)} от старта · ~${report.route?.etaMinutes??"?"} мин`));}}
  function renderRoute(route){currentRoute=route||null;if(!route){alternatives.replaceChildren();guardBox.hidden=true;guidance.hidden=true;planner.hidden=false;panel.dataset.mode="planner";return;}openPanel("planner");planner.hidden=false;guidance.hidden=true;renderGuard(route);alternatives.replaceChildren();for(const alternative of route.alternatives||[]){const row=button("",()=>onSelectAlternative?.(alternative.id),"navigation-alt");row.dataset.selected=String(alternative.id===route.selectedAlternativeId);const main=el("div","navigation-alt-main");main.append(el("strong","",`${fmtDistance(alternative.distanceKm)} · ${fmtDuration(alternative.durationSec)}`),el("span","",`ETA ${fmtEta(alternative.eta)}`));const difficulty=alternative.difficulty?.score==null?"сложность: данных мало":`сложность ${alternative.difficulty.score}/100`;const meta=el("div","navigation-alt-meta",`${difficulty} · трафик: ${alternative.trafficDelaySec==null?"нет источника":fmtDuration(alternative.trafficDelaySec)} · платные дороги: ${alternative.toll?.available?"есть расчёт":"цена недоступна"}`);row.append(main,meta);alternatives.append(row);}const start=button("Начать ведение",()=>onStart?.(),"primary");alternatives.append(start);renderLists(route);}
  function startGuidance(route=currentRoute){if(route)currentRoute=route;planner.hidden=true;alternatives.replaceChildren();guardBox.hidden=true;guidance.hidden=false;openPanel("guidance");renderLists(currentRoute);}
  function renderGuidance(model){if(!model)return;next.textContent=model.nextManeuver?.instruction||"Продолжайте по маршруту";offroute.textContent=model.offRoute?`Вы вне маршрута примерно на ${fmtDistance(model.distanceFromRouteKm)}. Перестройте маршрут.`:model.nextManeuver?.distanceToManeuverKm!=null?`Манёвр через ${fmtDistance(model.nextManeuver.distanceToManeuverKm)}`:"";metricDistance.replaceChildren(el("strong","",fmtDistance(model.remainingKm)),el("span","","осталось"));metricTime.replaceChildren(el("strong","",fmtDuration(model.remainingSec)),el("span","","в пути"));metricEta.replaceChildren(el("strong","",currentRoute?.selectedAlternative?.eta?fmtEta(currentRoute.selectedAlternative.eta):"—"),el("span","","ETA"));}
  function setMoving(value){panel.dataset.moving=String(Boolean(value));}
  function setBusy(text="Расчёт…"){state.textContent=text;}
  function setStateText(text){state.textContent=text;}
  function reset(){currentRoute=null;panel.hidden=true;launch.dataset.active="false";launch.setAttribute("aria-expanded","false");planner.hidden=false;guidance.hidden=true;alternatives.replaceChildren();parking.replaceChildren();roads.replaceChildren();guardBox.hidden=true;}
  return {panel,launch,openPanel,closePanel,setProviderStatus,setProfile,setDestination,getRequest,renderRoute,startGuidance,renderGuidance,setMoving,setBusy,setStateText,reset,getCurrentRoute(){return currentRoute;}};
}
